on:
    workflow_dispatch:
  
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo content
          uses: actions/checkout@v3
        
        - name: Determine next edition
          id: determine-edition
          run: |
            git fetch --tags
            git fetch origin --tags
            echo "EDITION=$(($(git describe --tags $(git rev-list --tags --max-count=1)) +1))" >> "$GITHUB_OUTPUT"
  
        - name: Create release
          uses: ncipollo/release-action@v1.13.0
          with:
            allowUpdates: true
            tag: ${{ steps.determine-edition.outputs.EDITION }}